language: node_js
node_js:
  - "iojs"
  - "7"
install:
  - cd backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..
script:
  - cd backend
  - npm run lint
  - npm test
  - cd ../frontend
  - npm test