language: node_js
node_js:
  - '11'
install:
  - cd models
  - npm install
  - cd ../backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..
script:
  - cd models
  - npm run lint
  - cd ../backend
  - npm run lint
  - npm test
  - cd ../frontend
  - npm run lint
  - npm test
