language: node_js
node_js:
  - '11'
install:
  - cd models
  - yarn install
  - yarn link
  - cd ../backend
  - yarn install
  - yarn link budget-r-models
  - cd ../frontend
  - yarn install
  - yarn link budget-r-models
  - cd ..
script:
  - cd models
  - yarn run lint
  - cd ../backend
  - yarn run lint
  - yarn test
  - cd ../frontend
  - yarn run lint
  - yarn test
